CREATE TABLE work_order_attachments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_order_id BIGINT NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    file_path VARCHAR(500) NOT NULL,
    file_size BIGINT,
    mime_type VARCHAR(100),
    uploaded_by_user_id BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_work_order_attachments_work_order_id FOREIGN KEY (work_order_id) REFERENCES work_orders (id),
    CONSTRAINT fk_work_order_attachments_uploaded_by_user_id FOREIGN KEY (uploaded_by_user_id) REFERENCES users (id)
);

CREATE INDEX idx_work_order_attachments_work_order_id ON work_order_attachments (work_order_id);