-- Bot interaction log genişletmesi + bildirim duplicate koruması

ALTER TABLE bot_interaction_logs ADD COLUMN direction VARCHAR(20);
ALTER TABLE bot_interaction_logs ADD COLUMN event_type VARCHAR(50);
ALTER TABLE bot_interaction_logs ADD COLUMN external_message_id VARCHAR(100);
ALTER TABLE bot_interaction_logs ADD COLUMN work_order_id BIGINT;
ALTER TABLE bot_interaction_logs ADD COLUMN error_message VARCHAR(255);
ALTER TABLE bot_interaction_logs ADD COLUMN message_summary VARCHAR(255);

CREATE UNIQUE INDEX uq_bot_interaction_external_message_id
    ON bot_interaction_logs (external_message_id);

CREATE TABLE notification_dedup (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_order_id BIGINT NOT NULL,
    event_type VARCHAR(50) NOT NULL,
    event_key VARCHAR(100) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_notification_dedup UNIQUE (work_order_id, event_type, event_key)
);

CREATE INDEX idx_notification_dedup_work_order_id ON notification_dedup (work_order_id);
