-- In-app bildirimler + WhatsApp outbox/retry

CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_user_id BIGINT,
    type VARCHAR(50) NOT NULL,
    title VARCHAR(200) NOT NULL,
    message VARCHAR(1000) NOT NULL,
    related_entity_type VARCHAR(50),
    related_entity_id BIGINT,
    channel VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    read_at TIMESTAMP,
    metadata_json TEXT,
    event_key VARCHAR(100) NOT NULL DEFAULT 'default',
    CONSTRAINT fk_notifications_recipient_user_id FOREIGN KEY (recipient_user_id) REFERENCES users (id),
    CONSTRAINT uq_notifications_user_event UNIQUE (recipient_user_id, type, related_entity_id, channel, event_key)
);

CREATE INDEX idx_notifications_recipient_created
    ON notifications (recipient_user_id, created_at DESC);

CREATE INDEX idx_notifications_recipient_unread
    ON notifications (recipient_user_id, is_read);

CREATE TABLE whatsapp_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_order_id BIGINT,
    event_type VARCHAR(50) NOT NULL,
    event_key VARCHAR(100) NOT NULL,
    recipient_phone VARCHAR(20) NOT NULL,
    payload TEXT NOT NULL,
    attempt_count INT NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMP,
    last_error VARCHAR(255),
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sent_at TIMESTAMP,
    claimed_at TIMESTAMP,
    claim_token VARCHAR(64),
    CONSTRAINT uq_whatsapp_outbox_event UNIQUE (work_order_id, event_type, event_key)
);

CREATE INDEX idx_whatsapp_outbox_pending
    ON whatsapp_outbox (status, next_attempt_at);
