CREATE TABLE roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    description VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_roles_name UNIQUE (name)
);

CREATE TABLE regions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id BIGINT NOT NULL,
    full_name VARCHAR(150) NOT NULL,
    email VARCHAR(150) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    phone VARCHAR(20),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT fk_users_role_id FOREIGN KEY (role_id) REFERENCES roles (id)
);

CREATE TABLE brands (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(255),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_brands_name UNIQUE (name)
);

CREATE TABLE customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(150) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    whatsapp_number VARCHAR(20),
    email VARCHAR(150),
    address TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE device_models (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    device_type VARCHAR(50) NOT NULL,
    general_warranty_months INT NOT NULL,
    parts_warranty_months INT NOT NULL,
    labor_warranty_months INT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_device_models_brand_id FOREIGN KEY (brand_id) REFERENCES brands (id)
);

CREATE TABLE technicians (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    region_id BIGINT NOT NULL,
    whatsapp_number VARCHAR(20) NOT NULL,
    current_workload INT NOT NULL DEFAULT 0,
    is_available BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_technicians_user_id UNIQUE (user_id),
    CONSTRAINT uq_technicians_whatsapp_number UNIQUE (whatsapp_number),
    CONSTRAINT fk_technicians_user_id FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_technicians_region_id FOREIGN KEY (region_id) REFERENCES regions (id)
);

CREATE TABLE devices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    model_id BIGINT NOT NULL,
    serial_number VARCHAR(150) NOT NULL,
    purchase_date DATE,
    installation_date DATE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_devices_serial_number UNIQUE (serial_number),
    CONSTRAINT fk_devices_customer_id FOREIGN KEY (customer_id) REFERENCES customers (id),
    CONSTRAINT fk_devices_model_id FOREIGN KEY (model_id) REFERENCES device_models (id)
);

CREATE TABLE warranty_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id BIGINT NOT NULL,
    warranty_type VARCHAR(30) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    description VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_warranty_records_device_id FOREIGN KEY (device_id) REFERENCES devices (id)
);

CREATE TABLE work_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    device_id BIGINT NOT NULL,
    technician_id BIGINT,
    created_by_user_id BIGINT NOT NULL,
    region_id BIGINT NOT NULL,
    description TEXT NOT NULL,
    status VARCHAR(30) NOT NULL,
    priority VARCHAR(20) NOT NULL,
    service_type VARCHAR(30) NOT NULL,
    assigned_at TIMESTAMP,
    waiting_for_parts_since TIMESTAMP,
    completed_at TIMESTAMP,
    closed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_work_orders_customer_id FOREIGN KEY (customer_id) REFERENCES customers (id),
    CONSTRAINT fk_work_orders_device_id FOREIGN KEY (device_id) REFERENCES devices (id),
    CONSTRAINT fk_work_orders_technician_id FOREIGN KEY (technician_id) REFERENCES technicians (id),
    CONSTRAINT fk_work_orders_created_by_user_id FOREIGN KEY (created_by_user_id) REFERENCES users (id),
    CONSTRAINT fk_work_orders_region_id FOREIGN KEY (region_id) REFERENCES regions (id)
);

CREATE TABLE work_order_status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_order_id BIGINT NOT NULL,
    changed_by_user_id BIGINT,
    old_status VARCHAR(30),
    new_status VARCHAR(30) NOT NULL,
    description VARCHAR(255),
    channel VARCHAR(30) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_work_order_status_history_work_order_id FOREIGN KEY (work_order_id) REFERENCES work_orders (id),
    CONSTRAINT fk_work_order_status_history_changed_by_user_id FOREIGN KEY (changed_by_user_id) REFERENCES users (id)
);

CREATE TABLE activity_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    technician_id BIGINT,
    action VARCHAR(100) NOT NULL,
    entity_name VARCHAR(100) NOT NULL,
    entity_id BIGINT NOT NULL,
    channel VARCHAR(30) NOT NULL,
    ip_address VARCHAR(50),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_activity_logs_user_id FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_activity_logs_technician_id FOREIGN KEY (technician_id) REFERENCES technicians (id)
);

CREATE TABLE bot_interaction_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    technician_id BIGINT,
    customer_id BIGINT,
    phone_number VARCHAR(20) NOT NULL,
    message_type VARCHAR(30) NOT NULL,
    incoming_message TEXT,
    outgoing_message TEXT,
    command VARCHAR(100),
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_bot_interaction_logs_technician_id FOREIGN KEY (technician_id) REFERENCES technicians (id),
    CONSTRAINT fk_bot_interaction_logs_customer_id FOREIGN KEY (customer_id) REFERENCES customers (id)
);

CREATE INDEX idx_users_role_id ON users (role_id);
CREATE INDEX idx_users_phone ON users (phone);
CREATE INDEX idx_technicians_region_id ON technicians (region_id);
CREATE INDEX idx_customers_phone ON customers (phone);
CREATE INDEX idx_customers_whatsapp_number ON customers (whatsapp_number);
CREATE INDEX idx_device_models_brand_id ON device_models (brand_id);
CREATE INDEX idx_devices_customer_id ON devices (customer_id);
CREATE INDEX idx_devices_model_id ON devices (model_id);
CREATE INDEX idx_devices_serial_number ON devices (serial_number);
CREATE INDEX idx_warranty_records_device_id ON warranty_records (device_id);
CREATE INDEX idx_work_orders_customer_id ON work_orders (customer_id);
CREATE INDEX idx_work_orders_device_id ON work_orders (device_id);
CREATE INDEX idx_work_orders_technician_id ON work_orders (technician_id);
CREATE INDEX idx_work_orders_region_id ON work_orders (region_id);
CREATE INDEX idx_work_orders_status ON work_orders (status);
CREATE INDEX idx_work_orders_created_at ON work_orders (created_at);
CREATE INDEX idx_work_order_status_history_work_order_id ON work_order_status_history (work_order_id);
CREATE INDEX idx_activity_logs_entity_name_entity_id ON activity_logs (entity_name, entity_id);
CREATE INDEX idx_activity_logs_created_at ON activity_logs (created_at);
CREATE INDEX idx_bot_interaction_logs_phone_number ON bot_interaction_logs (phone_number);
CREATE INDEX idx_bot_interaction_logs_created_at ON bot_interaction_logs (created_at);
